In [1]:
import cv2
import pickle
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from PIL import Image

In [2]:
new_model = tf.keras.models.load_model('model.tf')

In [3]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml') 

In [4]:
def detect(grey , frame):
    img = Image.fromarray(frame)
    img.save('1.png')
    x = image.load_img('1.png',target_size=(150,150))
    x = image.img_to_array(x)
    x = np.expand_dims(x,axis = 0)
    result = new_model.predict(x)
    if result[0][0] == 1:
        text = "Mask Detected"
    else:
        text = "Mask Not Detected"
    faces = face_cascade.detectMultiScale(grey , 1.3, 5)
    for (x,y , w,h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        cv2.putText(frame,text,(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,0),1,cv2.LINE_AA)
    return frame    

In [5]:
video_capture = cv2.VideoCapture(0)
while True:
    _,frame = video_capture.read()
    print(frame)
    grey = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    canvas = detect(grey,frame)
    cv2.namedWindow('Mask',cv2.WINDOW_NORMAL)
    cv2.resizeWindow('Mask', 1600,800)
    cv2.imshow('Mask',canvas)
    if cv2.waitKey(10) & 0xff == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[[127 139  88]
  [127 139  86]
  [124 137  80]
  ...
  [139 136  98]
  [135 139  94]
  [136 140  95]]

 [[128 140  89]
  [128 140  87]
  [124 137  80]
  ...
  [139 136  98]
  [133 137  92]
  [132 136  91]]

 [[137 143 107]
  [137 144 105]
  [132 140  97]
  ...
  [142 129 106]
  [138 131 101]
  [137 130 100]]

 ...

 [[210 198 145]
  [212 198 145]
  [212 198 145]
  ...
  [ 73  69  34]
  [ 73  69  34]
  [ 73  69  34]]

 [[216 202 149]
  [215 201 148]
  [215 201 148]
  ...
  [ 77  75  43]
  [ 72  71  41]
  [ 70  69  39]]

 [[216 202 149]
  [216 202 149]
  [215 201 148]
  ...
  [ 74  72  40]
  [ 71  70  40]
  [ 70  69  39]]]
[[[105 139  78]
  [104 132  91]
  [103 124 104]
  ...
  [134 130 106]
  [130 128 104]
  [129 127 103]]

 [[108 142  81]
  [106 134  93]
  [105 126 106]
  ...
  [132 128 104]
  [129 127 103]
  [130 128 104]]

 [[118 140  96]
  [117 135  99]
  [113 129 102]
  ...
  [134 124 107]
  [136 126 109]
  [138 128 111]]

 ...

 [[205 197 142]
  [206 198 143]
  [206 198 143]
  ..

[[[126 131 110]
  [120 128 102]
  [113 125  90]
  ...
  [125 116  93]
  [125 116  93]
  [126 117  94]]

 [[124 129 108]
  [120 128 102]
  [115 127  92]
  ...
  [125 116  93]
  [125 116  93]
  [126 117  94]]

 [[125 128 104]
  [125 129 101]
  [122 130  97]
  ...
  [124 119  89]
  [124 119  88]
  [125 120  89]]

 ...

 [[192 187 148]
  [193 186 147]
  [193 186 145]
  ...
  [122 111  68]
  [120 116  72]
  [111 107  63]]

 [[184 187 145]
  [185 187 145]
  [187 187 145]
  ...
  [129 112  72]
  [127 116  77]
  [123 112  73]]

 [[183 186 144]
  [184 186 144]
  [187 187 145]
  ...
  [128 111  71]
  [123 112  73]
  [123 112  73]]]
[[[141 130 107]
  [140 130 105]
  [137 127 100]
  ...
  [133 128  55]
  [132 129  47]
  [131 128  46]]

 [[140 129 106]
  [139 129 104]
  [136 126  99]
  ...
  [134 129  56]
  [133 130  48]
  [133 130  48]]

 [[141 127  98]
  [140 126  97]
  [136 125  94]
  ...
  [136 129  71]
  [137 130  67]
  [136 129  66]]

 ...

 [[194 184 147]
  [195 186 147]
  [196 187 146]
  ..

[[[116 136 120]
  [112 130 112]
  [108 124 105]
  ...
  [148 129 124]
  [150 127 123]
  [151 128 124]]

 [[113 133 117]
  [112 130 112]
  [110 126 107]
  ...
  [148 129 124]
  [149 126 122]
  [147 124 120]]

 [[110 134 118]
  [113 133 117]
  [113 131 113]
  ...
  [150 130 114]
  [152 128 110]
  [150 126 108]]

 ...

 [[202 197 148]
  [202 195 146]
  [201 194 145]
  ...
  [ 62  62  42]
  [ 59  64  43]
  [ 58  63  42]]

 [[203 196 148]
  [202 195 147]
  [201 194 145]
  ...
  [ 61  64  42]
  [ 59  66  44]
  [ 57  64  42]]

 [[203 196 148]
  [202 195 147]
  [201 194 145]
  ...
  [ 60  63  41]
  [ 60  67  45]
  [ 58  65  43]]]
[[[128 127 105]
  [132 127 106]
  [134 128 104]
  ...
  [130 131 109]
  [127 132 111]
  [131 136 115]]

 [[127 126 104]
  [131 126 105]
  [133 127 103]
  ...
  [130 131 109]
  [126 131 110]
  [128 133 112]]

 [[128 127  99]
  [130 127  99]
  [130 127  99]
  ...
  [129 132 110]
  [123 130 109]
  [123 130 109]]

 ...

 [[202 189 141]
  [204 191 144]
  [205 192 145]
  ..

[[[122 125 104]
  [122 123 101]
  [122 121  97]
  ...
  [144 127 111]
  [137 125 108]
  [132 120 103]]

 [[124 127 106]
  [125 126 104]
  [125 124 100]
  ...
  [146 129 113]
  [140 128 111]
  [138 126 109]]

 [[127 132 111]
  [128 131 110]
  [129 130 108]
  ...
  [149 138 117]
  [149 142 121]
  [153 146 125]]

 ...

 [[136 135  97]
  [136 135  96]
  [132 132  90]
  ...
  [138  97  42]
  [129  87  36]
  [126  84  33]]

 [[137 130  91]
  [137 130  89]
  [130 124  80]
  ...
  [141 102  46]
  [132  96  37]
  [130  94  35]]

 [[132 125  86]
  [131 124  83]
  [127 121  77]
  ...
  [143 104  48]
  [136 100  41]
  [132  96  37]]]
[[[144 131 128]
  [147 133 116]
  [148 135 102]
  ...
  [129 136 107]
  [128 139 100]
  [128 139 100]]

 [[144 131 128]
  [146 132 115]
  [146 133 100]
  ...
  [128 135 106]
  [126 137  98]
  [126 137  98]]

 [[138 136 118]
  [140 136 112]
  [138 133 103]
  ...
  [139 135 100]
  [140 136  92]
  [140 136  92]]

 ...

 [[126 133  93]
  [127 132  93]
  [125 130  91]
  ..

[[[144 135 122]
  [152 136 116]
  [154 135 105]
  ...
  [151 145 128]
  [151 149 129]
  [150 148 128]]

 [[144 135 122]
  [151 135 115]
  [153 134 104]
  ...
  [148 142 125]
  [147 145 125]
  [148 146 126]]

 [[142 141 105]
  [147 139 104]
  [148 136  99]
  ...
  [144 137 116]
  [145 140 119]
  [148 143 122]]

 ...

 [[161 156 126]
  [161 155 128]
  [160 157 129]
  ...
  [168 129  87]
  [167 129  84]
  [167 129  84]]

 [[167 154 130]
  [166 156 131]
  [163 155 128]
  ...
  [160 127  88]
  [161 126  85]
  [161 126  85]]

 [[168 155 131]
  [166 156 131]
  [163 155 128]
  ...
  [158 125  86]
  [161 126  85]
  [161 126  85]]]
[[[146 142  69]
  [146 142  66]
  [144 141  61]
  ...
  [167 147  79]
  [155 136  64]
  [163 144  72]]

 [[146 142  69]
  [146 142  66]
  [146 143  63]
  ...
  [162 142  74]
  [155 136  64]
  [160 141  69]]

 [[147 142  74]
  [147 141  78]
  [147 141  79]
  ...
  [161 139  81]
  [160 138  78]
  [162 140  80]]

 ...

 [[156 156 124]
  [157 157 125]
  [158 158 126]
  ..

[[[134 117  97]
  [136 120  97]
  [136 120  96]
  ...
  [165 139 120]
  [168 143 121]
  [168 143 121]]

 [[139 122 102]
  [140 124 101]
  [139 123  99]
  ...
  [162 136 117]
  [164 139 117]
  [164 139 117]]

 [[145 127 103]
  [146 128 102]
  [144 129 100]
  ...
  [160 132 113]
  [162 135 113]
  [162 135 113]]

 ...

 [[209 190 142]
  [209 190 142]
  [208 191 143]
  ...
  [ 67  68  56]
  [ 66  68  60]
  [ 66  68  60]]

 [[208 193 138]
  [208 192 139]
  [207 193 140]
  ...
  [ 68  68  60]
  [ 68  67  61]
  [ 67  66  60]]

 [[209 194 139]
  [209 193 140]
  [207 193 140]
  ...
  [ 69  69  61]
  [ 69  68  62]
  [ 68  67  61]]]
[[[144 123  91]
  [143 123  97]
  [139 122 102]
  ...
  [159 133 107]
  [160 132 104]
  [160 132 104]]

 [[145 124  92]
  [144 124  98]
  [140 123 103]
  ...
  [158 132 106]
  [158 130 102]
  [156 128 100]]

 [[145 129 106]
  [145 130 107]
  [143 130 107]
  ...
  [145 122  92]
  [151 126  94]
  [157 132 100]]

 ...

 [[209 192 144]
  [210 193 146]
  [210 192 148]
  ..